export const QuizData = [
    {
      "Quest": "A student claimed the diameter of a wire as $1.032cm$ on using Vernier Calipers Up-to what extent do you agree with it:",
      "Op1": "$1cm",
      "Op2": "$10cm",
      "Op3": "$1.03cm",
      "Op4": "$1.032cm",
      "UQuest": "ایک طالبعلم نے سکریو گیج سے کسی تار کا ڈایا میٹر $1.032cm$ معلوم کیا۔ آپ اس سے کس حد تک متفق ہیں:",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "The mass of a body:",
      "Op1": "Decrease when accelerated",
      "Op2": "Increase when accelerated",
      "Op3": "Decrease when moving with high velocity",
      "Op4": "Remains Constant",
      "UQuest": "ایک جسم کا ماس:",
      "UOp1": "ایکسلریٹ کرنے پر کم ہوتا ہے",
      "UOp2": "ایکسلریٹ کرنے پر زیادہ ہوتا ہے",
      "UOp3": "تیز ولاسٹی سے چلنے سے کم ہو جاتا ہے",
      "UOp4": "کانسٹنٹ ہوجاتی ",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "A string is stretched by two equal and opposite forces of $10N$ each, the tension in the string is:",
      "Op1": "$5N$",
      "Op2": "$20N$",
      "Op3": "$10N$",
      "Op4": "$0$",
      "UQuest": "ایک ڈوری کو دو مخالف فورسز کی مدد سے کھینچا جارہا ہے ہر ایک فورس کی مقدار $10N$ہے۔ ڈوری میں ٹینشن کتنا ہوگا:",
     
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "A force of $10N$ is making an angle of $30^{\\circ}$ with horizontal, its horizontal component will be\u003Cbr\u003E",
      "Op1": "$7N$",
      "Op2": "$8.7N$",
      "Op3": "$4N$",
      "Op4": "$5N$",
      "UQuest": "$10N$ کی ایک فورس $x-axis$ کے ساتھ $30^{\\circ}$ کا زاویہ بناتی ہے۔ اس فورس کا افقی کمپونینٹ ہو گا:",
      
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "Global positioning system (GPS) consists of earth satelite:",
      "Op1": "$23$",
      "Op2": "$24$",
      "Op3": "$25$",
      "Op4": "$26$",
      "UQuest": "گلوبل پوزیشننگ سسٹم (GPS) کل زمینی سیٹلائٹس پر مشتمل ہوتاہے:",
      
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "If the velocity of a body becomes double, then its kinetic energy will:",
      "Op1": "Becomes four times",
      "Op2": "Becomes Half",
      "Op3": "Becomes double",
      "Op4": "Remains the same",
      "UQuest": "اگر کسی جسم کی ولاسٹی دو گنا ہو جائے تو اس کی کائی نیٹک انرجی ہوگی:",
      "UOp1": "چار گناہ ہو جاتی ہے",
      "UOp2": "نصف ہو جاتی ہے",
      "UOp3": "دوگنا ہوجاتی ہے",
      "UOp4": "کانسٹنٹ ہوجاتی ہے",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "In Einstein's mass-energy equation \"$C$\" is the:",
      "Op1": "Speed of electron",
      "Op2": "Speed of earth",
      "Op3": "Speed of sound",
      "Op4": "Speed of light",
      "UQuest": "آئن سٹائن کی ماس انرجی مساوات میں '$C$' ظاہر کرتا ہے:",
      "UOp1": "الیکڑون کی سپیڈ",
      "UOp2": "زمین کی سپیڈ",
      "UOp3": "آواز کی سپیڈ",
      "UOp4": "روشنی کی سپیڈ",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "SI unit of pressure is Pascal which is equal to:",
      "Op1": "$1\\times10^{1}Nm^{-2}$",
      "Op2": "$1\\times10^{2}Nm^{-2}$",
      "Op3": "$1\\times10^{0}Nm^{-2}$",
      "Op4": "$1\\times10^{3}Nm^{-2}$",
      "UQuest": "سسٹم انٹرنیشنل میں پریشر کا یونٹ پاسکل ہے اور ایک پاسکل برابر ہوتا ہے:",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "Heat capacity of $5 kg$ of water will be:",
      "Op1": "$21000JK^{-1}$",
      "Op2": "$22000JK^{-1}$",
      "Op3": "$23000JK^{-1}$",
      "Op4": "$24000JK^{-1}$",
      "UQuest": "5 کلوگرام پانی کی حرارتی گنجائش ہوگی:",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "Actual value of latent heat of vaporization of one kg water at $100 ^{\\circ}C$ is:",
      "Op1": "$3.26\\times10^6 JKg^{-1}$",
      "Op2": "$2.26\\times10^6 JKg^{-1}$",
      "Op3": "$4.26\\times10^6 JKg^{-1}$",
      "Op4": "$5.26\\times10^6 JKg^{-1}$",
      "UQuest": "$100 ^{\\circ}C$ ٹمپریچر پر ایک کلو گرام پانی ویپورائزیشن کی مخفی حرارت کی حقیقی قیمت ہوتی ہے:",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "Which of the following materials has large value of temperature co-efficient of linear expansion:",
      "Op1": "Steel",
      "Op2": "Brass",
      "Op3": "Gold",
      "Op4": "Aluminium",
      "UQuest": "درج ذیل میں سے کس میٹریل کے طولی پھیلاؤ کے کوایفی شینٹ کی قیمت زیادہ ہوتی ہے:",
      "UOp1": "سٹیل",
      "UOp2": "براس",
      "UOp3": "گولڈ",
      "UOp4": "ایلومینیم",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    },
    {
      "Quest": "$50Kmh^{-1}$ will be equal to:",
      "Op1": "$13.88ms^{-1}$",
      "Op2": "$14.88ms^{-1}$",
      "Op3": "$15.88ms^{-1}$",
      "Op4": "$16.88ms^{-1}$",
      "UQuest": "$50Kmh^{-1}$ برابر ہوگا:",
      "Year": 9,
      "Subject": "Physics",
      "BISE": "LHR2024",
      "Type": "MCQ"
    }
  ]